### ISSUE TITLE
unexpected argument when trying to add a '|' as a string in a datagroup

### ISSUE THREAD

**Issue by matthewmdn** [f5devcentral/f5-puppet#25]
the error when running `puppet device -v --user=root`: 

> ERROR:<some path>/F5_datagroup[/Common/test2_bl_escape_characters]/ensure: change from absent to present failed: Could not set 'present' on ensure: REST failure: HTTP status code 400 detected.  Body of failure is: {"code":400,"message":"unexpected argument \"|\"","errorStack":[],"apiError":26214401} at <some path>/global_datagroups.pp:111

The relevant code is:
`  f5_datagroup { '/Common/test2_bl_escape_characters':
  ensure  => 'present',
  type    => 'string',
  records => [
    {
      'data' => '!',
      'name' => '!'
      },
    {
      'data' => '$',
      'name' => '$'
      },
    {
      'data' => ';',
      'name' => ';'
      },
    {
      'data' => '<',
      'name' => '<'
      },
    {
      'data' => '>',
      'name' => '>'
      },
    {
      'data' => '\\',
      'name' => '\\'
      },
    {
      'data' => '\|',
      'name' => '\|'
      }
    ],
  }`

From what it looks like, I need to escape the | with something. I've tried `'|'` and `'\|'` both. I got the code from exporting an existing datagroup with `puppet resource` , so it should "just work".

**Comment by ericzji** [comment]
@matthewmdn Your issue is about how to handle the data group special characters. Please allow me to reach out to F5 REST API team, and will get back to you.

**Comment by ericzji** [comment]
@matthewmdn 
The workaround is to add an extra space to the end of the value, in your case:
     { 'data' => '\\ ', 'name' => '\\ ' },
     { 'data' => '| ', 'name' => '| ' },

thanks

**Comment by matthewmdn** [comment]
Great! I'll give it a try

**Comment by matthewmdn** [comment]
That did it

**Comment by ericzji** [comment]
Excellent
