### ISSUE TITLE
f5_command does not execute tmsh

### ISSUE THREAD

**Issue by s-seitz** [f5devcentral/f5-puppet#63]
`f5_command { '/Common/tmsh':`
`    ensure => present,`
`    tmsh   => "tmsh save /sys ucs backup-${current_time}.ucs",`
`}`
shows following result
`Notice: /Stage[main]/Profile::F5::Server/F5_command[/Common/tmsh]/ensure: created (corrective)`
but does obviously nothing on the respective F5 node.

Executing the same tmsh command at the CLI works as expected.

We're using 
`mod 'f5/f5',`
`  :git => 'https://github.com/f5devcentral/f5-puppet.git',`
`  :commit => 'fd979b78dbcba76c261ef3a575d1ae85e6690f10'`

**Comment by harung** [comment]
Check the log files on the F5 node. You may see an error there. You will not see the errors in the puppet run.

**Comment by harung** [comment]
I use f5_command successfully to create and modify datagroups.

**Comment by s-seitz** [comment]
Thank You for the feedback. I've found the issue using tmsh interactively. F5's save /sys ucs [file] triggered a "license issue", which has been fixed by a hotfix release.
