### ISSUE TITLE
f5_profileclientssl

### ISSUE THREAD

**Issue by ptiggerdine** [f5devcentral/f5-puppet#73]
f5_Profileclientssl is missing a "," after the chain stanza

                 key:                   profile['key'],
              chain:                   profile['chain']  <--
        proxy_ssl:                   profile['proxySsl'],

The impact is that when chain is added to manifest proxyssl needs to be stipulated.

**Comment by ptiggerdine** [comment]
resolved by the following commit
https://github.com/f5devcentral/f5-puppet/commit/59b7ee45769b968733e4976a276af03b0383e7dc

**Comment by amccrea** [comment]
This was fixed but never got merged into any tagged version. @n3mawashi Can I request this repo roll another tag to get this fix in? The last tag (1.9.1) is from 2019.

**Comment by n3mawashi** [comment]
yes please :)
